<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_conveyor_belt">
    
    <!-- Material definitions -->
    <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
    </material>
    <material name="white">
        <color rgba="1.0 1.0 1.0 1.0"/>
    </material>
    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>

    <!-- Link properties -->
    <xacro:property name="base_length" value="2.0"/>
    <xacro:property name="base_width" value="0.5"/>
    <xacro:property name="base_height" value="0.2"/> 
    <xacro:property name="bar_length" value="0.6"/>
    <xacro:property name="bar_width" value="0.2"/>
    <xacro:property name="bar_height" value="0.1"/>
    <xacro:property name="sphere_radius" value="0.05"/> 
    <xacro:property name="sphere_offset" value="0.4"/>
    <xacro:property name="pi_" value="3.14159265359"/>

    <!-- Predefine links -->
    <xacro:macro name="bar_link" params="name length width height material">
        <link name="${name}">
            <visual>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${material}"/> 
            </visual>
            <collision>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="sphere_link" params="name radius material">
        <link name="${name}">
            <visual>
                <geometry>
                    <sphere radius="${radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
                <material name="${material}"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${radius}"/>
                </geometry>
                <origin rpy="0 0 0" xyz="0 0 0"/>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="fixed_joint" params="name parent child x y z">
        <joint name="${name}" type="fixed">
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
        </joint>
    </xacro:macro>

    <xacro:macro name="revolute_joint" params="name parent child x y z lower_limit upper_limit">
        <joint name="${name}" type="revolute">
            <parent link="${parent}"/>
            <child link="${child}"/>
            <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
            <axis xyz="0 0 1"/>
            <limit lower="${lower_limit}" upper="${upper_limit}" effort="100" velocity="10"/>
        </joint>
    </xacro:macro>

    <!-- Call macros -->
    <xacro:bar_link name="base_link" length="${base_length}" width="${base_width}" height="${base_height}" material="grey"/>

    <!-- Joints -->
    <xacro:macro name="axle_and_bar" params="index">
        <xacro:property name="x_pos" value="${-base_length/2 + sphere_offset * (index + 0.5)}"/>

        <xacro:sphere_link name="axle_${index}" radius="${sphere_radius}" material="black"/>

        <xacro:fixed_joint name="base_to_axle_${index}" parent="base_link" child="axle_${index}" x="${x_pos}" y="0" z="${-base_height/2 - sphere_radius}"/>

        <xacro:bar_link name="bar_${index}" length="${bar_length}" width="${bar_width}" height="${bar_height}" material="white"/>

        <xacro:revolute_joint name="axle_${index}_to_bar_${index}" parent="axle_${index}" child="bar_${index}" x="0" y="0" z="${-sphere_radius - bar_height/2}" lower_limit="${-pi_/4}" upper_limit="${pi_/4}"/>
    </xacro:macro>

    <!-- Call joints -->
    <xacro:axle_and_bar index="0"/>
    <xacro:axle_and_bar index="1"/>
    <xacro:axle_and_bar index="2"/>
    <xacro:axle_and_bar index="3"/>
    
</robot>